# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord-import'
gem 'alba'
gem 'bootsnap', require: false
gem 'closure_tree'
gem 'dotenv-rails'
gem 'faraday-retry'
gem 'jwt'
gem 'octokit'
gem 'pagy'
gem 'pg', '~> 1.6'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 8.1.1'
gem 'solid_cache'
gem 'solid_queue'

group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
  gem 'simplecov', require: false
end

gem 'dockerfile-rails', '>= 1.7', group: :development
